### ISSUE TITLE
Error in production

### ISSUE THREAD

**Issue by vhtellez** [ctlabvn/Recaptcha#18] opened 2018-03-09 20:49 UTC
this is the error log 

fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
fopen(): Failed to enable crypto
fopen(https://www.google.com/recaptcha/api/siteverify): failed to open stream: operation failed

**Comment by ADmad** [comment] 2018-03-09 20:52
Duplicate of #15.

**Closed as completed** 2018-04-26 16:20 UTC
